name: CI

on:
  push:
    branches:
      - main
      - 'renovate/**'
  pull_request:

jobs:
  test_python:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: demo.settings
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - id: pip-cache
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/runtime.txt') }}-${{ hashFiles('**/requirements.txt') }}
      - if: steps.pip-cache.outputs.cache-hit != 'true'
        run: python -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt
      - run: flake8 demo
      - run: black demo --check
      - run: python manage.py check
      - run: python manage.py render_patterns
  test_node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - id: node-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/.nvmrc') }}-${{ hashFiles('**/package-lock.json') }}
      - if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm run lint:js
      - run: npm run lint:format
      - run: npm run build
  test_storyshots:
    runs-on: ubuntu-latest
    needs: [test_python, test_node]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - id: node-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/.nvmrc') }}-${{ hashFiles('**/package-lock.json') }}
      - id: pip-cache
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/runtime.txt') }}-${{ hashFiles('**/requirements.txt') }}-
      - run: source .venv/bin/activate
      - run: python manage.py runserver 0:8001 &
      - run: npm run test
